#!/usr/bin/perl

use strict;
use warnings;

use Curses;
use Time::HiRes qw( usleep );
use Net::Ping;

# Which hosts should be pinged?
my @hostlist = qw / 127.0.0.1 127.0.0.2 127.0.0.3 /;

# Initialize the screen
initscr;
my $win = new Curses;

# Initialize ping environment
my $ping = Net::Ping->new();
$ping->hires();

# Screen settings
my $first_line_y = 5;
# For iterating the host list
my $host_nr;

$win->addstr( 2, 0, "Hit Ctrl+C to exit anytime." );

# Print host names / IP addresses
$host_nr = 0;
foreach my $host ( @hostlist ) {
    $win->addstr( $first_line_y + $host_nr, 0, $host );
    $host_nr++;
}
$win->refresh;

# Ping each host
$host_nr = 0;
foreach my $host ( @hostlist ) {

    my ( $ret, $dur, $ip ) = $ping->ping( $host, 2 );
    
    my $dur_s = sprintf( "%.7f", $dur );
    $win->addstr( $first_line_y + $host_nr, 15, $dur_s );
    $win->refresh;

    usleep( 500_000 );

    $host_nr++;

}

# Terminate curses
endwin;

